version: '3'

services:
  postgres1:
    image: postgres:16
    ports:
      - "5436:5436"
    env_file:
      - .env1
    volumes:
        - controltowerpt_postgres_data:/var/lib/postgresql/data


  controltowerpt:
    image: ghcr.io/asecapocotesteable/controltowerpt:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres1
    env_file:
        - .env1

  postgres2:
    image: postgres:16
    ports:
      - "5433:5433"
    env_file:
      - .env2
    volumes:
        - deliveryapi_postgres_data:/var/lib/postgresql/data

  deliveryapi:
    image: ghcr.io/asecapocotesteable/deliveryapi:latest
    ports:
      - "8082:8082"
    depends_on:
      - postgres2
    env_file:
      - .env2

  postgres3:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env3
    volumes:
      - warehouseapi_postgres_data:/var/lib/postgresql/data

  warehouseapi:
    image: ghcr.io/asecapocotesteable/warehouseapi:latest
    ports:
      - "8081:8081"
    depends_on:
      - postgres3
    env_file:
      - .env3

  cartweb:
    image: ghcr.io/asecapocotesteable/cartweb:latest
    ports:
      - "3001:3001"

  adminweb:
    image: ghcr.io/asecapocotesteable/adminweb:latest
    ports:
      - "3000:3000"

  warehouseweb:
    image: ghcr.io/asecapocotesteable/warehouseweb:latest
    ports:
      - "3002:3002"

  deliverymobile:
    image: ghcr.io/asecapocotesteable/deliverymobile:latest
    ports:
      - "3008:3008"

volumes:
  controltowerpt_postgres_data:
  deliveryapi_postgres_data:
  warehouseapi_postgres_data: