version: '3'

services:
  postgres1:
    image: postgres:16
    ports:
      - "5436:5436"
    env_file:
      - .env1
    volumes:
        - controltowerpt_postgres_data:/var/lib/postgresql/data


  controltowerpt:
    image: ghcr.io/gonza69420/controltowerpt:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres1
    env_file:
        - .env1

  postgres2:
    image: postgres:16
    ports:
      - "5433:5433"
    env_file:
      - .env2
    volumes:
        - deliveryapi_postgres_data:/var/lib/postgresql/data

  deliveryapi:
    image: ghcr.io/gonza69420/deliveryapi:latest
    ports:
      - "8082:8082"
    depends_on:
      - postgres2
    env_file:
      - .env2

  cartweb:
    image: ghcr.io/gonza69420/cartweb:latest
    ports:
      - "3001:3001"

  adminweb:
    image: ghcr.io/gonza69420/adminweb:latest
    ports:
      - "3000:3000"

  warehouseweb:
    image: ghcr.io/gonza69420/warehouseweb:latest
    ports:
      - "3002:3002"

volumes:
  controltowerpt_postgres_data:
  deliveryapi_postgres_data: